# Generated by Django 4.0.4 on 2022-05-12 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.IntegerField()),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('total_posts', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic_url', models.URLField(blank=True, null=True)),
                ('profile_pic_url_hd', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('fbid', models.IntegerField(blank=True, null=True)),
                ('biography', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('following', models.IntegerField(blank=True, null=True)),
                ('is_business_account', models.BooleanField(default=False)),
                ('is_professional_account', models.BooleanField(default=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('connected_fb_page', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'InstaUsers',
                'ordering': ('-updated_at',),
            },
        ),
    ]
