# Generated by Django 4.0.4 on 2022-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insta_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
