# Generated by Django 4.0.4 on 2022-05-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerrelation',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_person', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='followerrelation',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_person', to='webapp.user'),
        ),
    ]
