# Generated by Django 4.0.4 on 2022-05-13 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_user_insta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2200)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('shortcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('taken_at', models.PositiveIntegerField()),
                ('comments_count', models.PositiveIntegerField()),
                ('likes_count', models.PositiveIntegerField()),
                ('filter_type', models.PositiveSmallIntegerField(default=0)),
                ('media_type', models.PositiveSmallIntegerField(default=1)),
                ('original_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('caption_is_edited', models.BooleanField(default=False)),
                ('is_paid_partnership', models.BooleanField(default=False)),
                ('comment_likes_enabled', models.BooleanField(default=False)),
                ('is_unified_video', models.BooleanField(default=False)),
                ('is_post_live', models.BooleanField(default=False)),
                ('commerciality_status', models.CharField(default='not_commericial', max_length=30)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=2200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', related_query_name='has_post', to='webapp.location')),
            ],
            options={
                'verbose_name_plural': 'posts',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('taken_at', models.PositiveIntegerField()),
                ('expiring_at', models.PositiveIntegerField()),
                ('is_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='posts_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='fbid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='insta_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('has_audio', models.BooleanField()),
                ('video_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', related_query_name='has_video', to='webapp.post')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', related_query_name='has_video', to='webapp.story')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', related_query_name='has_story', to='webapp.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', related_query_name='has_post', to='webapp.user'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='has_image', to='webapp.post')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='has_image', to='webapp.story')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('thumbnail_url', models.URLField()),
                ('cropped_thumbnail_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlist', related_query_name='has_highlight', to='webapp.user')),
            ],
        ),
    ]
