# Generated by Django 4.0.4 on 2022-05-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_location_post_story_remove_user_total_posts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('lng', 'lat'), name='loc_unique'),
        ),
    ]
