# Generated by Django 4.0.4 on 2022-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_followed_at_followerrelation_follows_till'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followerrelation',
            constraint=models.UniqueConstraint(fields=('to_person', 'from_person'), name='follow_rel_unique'),
        ),
    ]
