# Generated by Django 4.0.4 on 2022-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_location_options_location_loc_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-width', '-updated_at'), 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-width', '-updated_at'), 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='post',
            name='is_post_live',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
