# Generated by Django 4.0.4 on 2022-05-15 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_followerrelation_follow_rel_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerrelation',
            old_name='follows_till',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='followerrelation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
