# Generated by Django 4.0.4 on 2022-05-16 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_follows_till_followerrelation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfollowerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='unfollower',
            field=models.ManyToManyField(related_name='unfollows', through='webapp.UnfollowerRelation', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='followerrelation',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_from_person', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='followerrelation',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_to_person', to='webapp.user'),
        ),
        migrations.AddField(
            model_name='unfollowerrelation',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unfollow_from_person', to='webapp.user'),
        ),
        migrations.AddField(
            model_name='unfollowerrelation',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unfollow_to_person', to='webapp.user'),
        ),
        migrations.AddConstraint(
            model_name='unfollowerrelation',
            constraint=models.UniqueConstraint(fields=('to_person', 'from_person'), name='unfollow_rel_unique'),
        ),
    ]
