# Generated by Django 4.0.4 on 2022-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
