# Generated by Django 4.0.4 on 2022-05-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_imagevideobase64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagevideobase64',
            name='base64',
            field=models.TextField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagevideobase64',
            name='image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images'),
        ),
    ]
