# Generated by Django 4.0.4 on 2022-05-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_imagevideobase64_base64_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageVideoBase64',
            new_name='ImageBase64',
        ),
    ]
