# Generated by Django 4.0.4 on 2022-05-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_imagevideobase64_imagebase64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebase64',
            name='url',
            field=models.URLField(max_length=2200, unique=True),
        ),
    ]
