# Generated by Django 4.0.4 on 2022-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_config_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='favicon',
            new_name='favicon_16x16',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='logo',
            new_name='favicon_32x32',
        ),
        migrations.AddField(
            model_name='config',
            name='favicon_apple',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
        migrations.AddField(
            model_name='config',
            name='share_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/defaults'),
        ),
    ]
