# Generated by Django 4.0.4 on 2022-05-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_favicon_config_favicon_16x16_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='contact_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
