# Generated by Django 4.0.4 on 2022-05-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_imagebase64_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebase64',
            name='filename',
            field=models.CharField(blank=True, editable=False, max_length=2200, null=True),
        ),
    ]
