# Generated by Django 4.0.4 on 2022-05-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_config_contact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='contact_description',
        ),
    ]
