# Generated by Django 4.0.4 on 2022-05-14 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_imagebase64_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebase64',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'ImagesB64'},
        ),
        migrations.AlterField(
            model_name='imagebase64',
            name='base64',
            field=models.TextField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagebase64',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='imagebase64',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
