# Generated by Django 4.0.4 on 2022-05-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_config_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shortcode',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
