# Generated by Django 4.0.4 on 2022-05-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_post_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shortcode',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CarouselMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('media_type', models.PositiveSmallIntegerField(default=1)),
                ('original_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm', related_query_name='has_cm', to='webapp.post')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='cm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', related_query_name='has_image', to='webapp.carouselmedia'),
        ),
    ]
