# Generated by Django 4.0.5 on 2022-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=2083),
        ),
    ]
