# Generated by Django 4.0.5 on 2022-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_image_url_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselmedia',
            name='insta_id',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='insta_id',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='insta_id',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='insta_id',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='insta_id',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
